name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: mbstring, bcmath, pdo, curl

    - name: Copy .env
      run: cp .env.example .env
      working-directory: ./src/backend

    - name: Install Dependencies
      run: composer install --no-interaction --prefer-dist --no-scripts
      working-directory: ./src/backend

    - name: Generate App Key
      run: php artisan key:generate
      working-directory: ./src/backend

    - name: Set Permissions
      run: chmod -R 777 storage bootstrap/cache
      working-directory: ./src/backend

    - name: Create SQLite Database
      run: |
        mkdir -p database
        touch database/database.sqlite
      working-directory: ./src/backend

    - name: Run Tests (PHPUnit or Pest)
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test
      working-directory: ./src/backend
