name: Node.js CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/frontend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]  # gunakan versi Node.js yang sesuai

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: src/frontend/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: src/frontend

      - name: Build project
        run: npm run build
        working-directory: src/frontend

      - name: Run Integration Tests
        run: npm run test:integration
        working-directory: src/frontend
