name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]  # sesuai Node kamu versi 22.14.0

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: src/frontend/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./src/frontend

      - name: Build project
        run: npm run build
        working-directory: ./src/frontend

      - name: Run Integration Tests
        run: npm run test:integration
        working-directory: ./src/frontend
